### ISSUE TITLE
Chat is currently not available

### ISSUE THREAD

**Issue by dewleys** [TheRealAyCe/ubisoftconnect-win7fix#3]
Hello there. Thank you, the app is working and I can send requests for an invitation to the group.
My problem is when i send an invitation via chat in overlay, then the chat becomes unavailable in overlay. I can send invitation requests to the group via the Friends tab in overlay and can send requests via chat, which is available in Ubisoft Connect on the desktop.
Please tell me how to use the program properly? Do you only need to communicate via Ubisoft Connect on your desktop or can you communicate via overlay in the game?
After the chat in overlay becomes unavailable, you have to collapse the game (Alt + Tab) to respond to messages.
![For Honor2022-1-23-0-26-38](https://user-images.githubusercontent.com/98238767/150672922-220b01bb-ecd3-454b-a90b-b9c938f6b2ff.png)
Uplay version 10632. Run as Admin roots. Im tried v1 and v2 your app. Same result.

**Comment by TheRealAyCe** [comment]
I can't speak to how the overlay handles things. Can you send me errors from the overlay log?

**Comment by dewleys** [comment]
Sure.
`[ 1232]  2022-01-23 00:24:00      [ 3576]      ERROR      ReadableSharedMemory.cpp (48)                    Failed to get pointer for shared memory with name overlay_view_1232 and size 7056000. Error is 5.
[ 1232]  2022-01-23 00:24:00      [ 3576]      ERROR      Overlay.cpp (553)                                Unable to open shared memory overlay_view_1232 with size 7056000.`
and now - cant write message from overlay
`[ 2688]  2022-01-23 18:16:06      [ 3304]      DEBUG      Win32InputHooks.cpp (2207)                       Failed get language hotkey toggle, using default sequence
[ 2688]  2022-01-23 18:16:06      [ 3304]      DEBUG      Win32InputHooks.cpp (2215)                       Failed get layout hotkey toggle, using default sequence
[ 2688]  2022-01-23 18:16:07      [ 3304]      DEBUG      Win32InputHooks.cpp (2207)                       Failed get language hotkey toggle, using default sequence
[ 2688]  2022-01-23 18:16:07      [ 3304]      DEBUG      Win32InputHooks.cpp (2215)                       Failed get layout hotkey toggle, using default sequence`
![1825](https://user-images.githubusercontent.com/98238767/150688022-ee082af8-ba8c-4902-8c43-188ed10ae4db.png)

**Comment by TheRealAyCe** [comment]
Is that all? These errors do not seem HTTP-specific to me. It's possible that the overlay does not want to communicate via the proxy, in which case I recommend only using the Ubisoft Connect chat/invite/group system. It may also stop working due to other things Win7 related, or Ubisoft making programming mistakes with shared memory. With these error logs, I don't have a clue what is going on.

I cannot test the overlay myself at the moment. Can you check if the request counter in the ubisoftconnect-win7fix window is going up when you do overlay chat stuff? In v2, you can check if you see requests that do not have "-> 200" in the Requests window, the window that opens when you click the "Show" button. All requests should have the 200.

I'd love to fix it, but right now I think the problem is that the overlay has some internal crashes which I can do nothing about.

**Comment by dewleys** [comment]
You're right. There are only 200 events in logs.
It's sad that Ubisoft stopped supporting Windows 7. Thank you for being able to talk to friends in Ubi Connect.
